baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ibrahim Eldesoki"
theme = "yinyang"
[params]
 headTitle = "Ibrahim Eldesoki"
 name = "Ibrahim Eldesoki"

# Yinyang social links
[[params.socials]]
name = "Github"
link = "https://github.com/ibrahimeldesoki"
[[params.socials]]
name = "Twitter"
link = "https://twitter.com/eldesokii96"
[[params.socials]]
name = "Linkedin"
link = "https://www.linkedin.com/in/i-eldesoki1/"

